import Head from 'next/head'
import Contact from '../Components/Contact'
import styles from '../styles/Contact.module.css'

const contact = ({ currentTheme }) => {

    return (
        <>
            <Head>
                <title>Contact Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.contactFullDiv}>
                <Contact currentTheme={currentTheme} />
            </div>
        </>
    )
}

export default contact
