import Head from 'next/head'
import Contact from '../Components/Contact'

const contact = ({ currentTheme }) => {

    return (
        <>
            <Head>
                <title>Contact Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <Contact currentTheme={currentTheme} />
            </div>
        </>
    )
}

export default contact
