import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from "react"
import { lightTheme, darkTheme, GlobalStyles } from "../ThemeConfig" 

export default function Home({theme}) {

  const [currentTheme, setCurrentTheme] = useState(theme)

  useEffect(() => {
    setCurrentTheme(theme)
  }, [theme])

  const themeObject = currentTheme==='light' ? lightTheme : darkTheme

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Hello There
      <div className={styles.colordiv} style={{ background: themeObject.body}}></div>
      <div className={styles.colordiv} style={{ background: themeObject.secondary}}></div>
      <div className={styles.colordiv} style={{ background: themeObject.tertiary}}></div>
      <div className={styles.colordiv} style={{ background: themeObject.accent}}></div>
    </div>
  )
}
