import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home({currentTheme}) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div className={styles.colordiv} style={{ background: currentTheme.body}}>BODY</div>
      <div className={styles.colordiv} style={{ background: currentTheme.secondary}}>SECONDARY</div>
      <div className={styles.colordiv} style={{ background: currentTheme.tertiary}}>TERTIARY</div>
      <div className={styles.colordiv} style={{ background: currentTheme.accent}}>ACCENT</div> */}
    </div>
  )
}
