import Head from 'next/head'
import HomePage from '../Components/HomePage'

export default function Home({currentTheme}) {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage currentTheme={currentTheme} />
    </div>
  )
}
