import Head from 'next/head'
import Work from '../Components/Work';

const work = ({ currentTheme }) => {
    return (
        <>
            <Head>
                <title>Work Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <Work currentTheme={currentTheme}/>
            </div>
        </>
    )
}

export default work
